{
 "title": "smart_warehouse",
 "time": { "from": "2026-04-02T14:00:31.779Z", "to": "2026-04-02T14:10:31.779Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "sector_id",
    "label": "Seleziona settore",
    "query": "SELECT name AS __text, sector_id AS __value FROM Sectors ORDER BY sector_id;"
   },
   {
    "name": "product_id",
    "label": "Seleziona prodotto",
    "query": "SELECT name AS __text, product_id AS __value FROM Products ORDER BY name;"
   }
  ]
 },
 "panels": [
  { "title": "Statistiche globali", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storico generale movimentazioni magazzino",
   "type": "table",
   "description": "mostra lo storico riguardante tutti i settori dei movimenti di magazzino",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  l.timestamp AS \"Data/Ora\",\n  u.username AS \"Utente\",\n  p.name AS \"Prodotto\",\n  s.name AS \"Settore\",\n  l.quantity AS \"Quantità\"\nFROM StockMovementsLog l\nJOIN Users u ON l.user_id = u.user_id\nJOIN Products p ON l.product_id = p.product_id\nJOIN Sectors s ON l.sector_id = s.sector_id\nORDER BY l.timestamp DESC\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Prodotti al di sotto della soglia di riordino",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  p.name AS \"prodotto\",\n  SUM(i.quantity) AS \"stock_attuale\",\n  p.reorder_threshold AS \"soglia\"\nFROM Inventory i\nJOIN Products p ON i.product_id = p.product_id\nGROUP BY p.product_id, p.name, p.reorder_threshold\nHAVING SUM(i.quantity) < p.reorder_threshold\nORDER BY stock_attuale ASC;"
    }
   ]
  },
  {
   "title": "Inventario generale",
   "type": "barchart",
   "description": "mostra la quantità totale di ogni prodotto considerando tutti i settori del magazzino",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  p.name AS \"prodotto\",\n  SUM(i.quantity) AS \"totale\"\nFROM Inventory i\nJOIN Products p ON i.product_id = p.product_id\nGROUP BY p.name\nORDER BY totale DESC;"
    }
   ]
  },
  {
   "title": "Numero di accessi negati negli ultimi 7 giorni",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  COUNT(*) \nFROM AccessLogs\nWHERE access_granted = false \n  AND timestamp >= NOW() - INTERVAL '7 days';"
    }
   ]
  },
  {
   "title": "Dettaglio accessi negati",
   "type": "table",
   "description": "mostra il dettaglio degli accessi negati ai settori di magzzino negli ultimi 7 giorni",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  u.username AS \"Utente\", \n  s.name AS \"Settore\",\n  a.timestamp AS \"Data/Ora\"\nFROM AccessLogs a\nJOIN Users u ON a.user_id = u.user_id\nJOIN Sectors s ON a.sector_id = s.sector_id\nWHERE access_granted = false \n  AND timestamp >= NOW() - INTERVAL '7 days';"
    }
   ]
  },
  {
   "title": "Elenco riordini",
   "type": "table",
   "description": "vengono mostrati tutti i riordini merce, sia manuali che automatici",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "smart_warehouse",
     "rawSql": "SELECT \n  p.name AS \"Prodotto\",\n  u.username AS \"Riordinante\",\n  quantity AS \"Quantità\",\n  timestamp_created AS \"Data/Ora\"\nFROM supplierorders AS so\nJOIN Users AS u ON so.user_id = u.user_id\nJOIN Products AS p ON so.product_id = p.product_id\nORDER BY timestamp_created DESC"
    }
   ]
  },
  {
   "title": "Dettaglio settori",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lista prodotti settore: $sector_id",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "smart_warehouse",
       "rawSql": "SELECT \n  p.name AS \"prodotto\",\n  SUM(i.quantity) AS \"totale\"\nFROM Inventory i\nJOIN Products p ON i.product_id = p.product_id\nWHERE i.sector_id = $sector_id -- Grafana sostituirà questo con il valore del menu a tendina\nGROUP BY p.name\nORDER BY totale DESC;"
      }
     ]
    },
    {
     "title": "Movimentazione prodotti per settore: $sector_id",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "dataset": "smart_warehouse",
       "rawSql": "SELECT \n  l.timestamp AS \"Data/Ora\",\n  u.username AS \"Utente\",\n  p.name AS \"Prodotto\",\n  l.quantity AS \"Quantità\"\nFROM StockMovementsLog l\nJOIN Users u ON l.user_id = u.user_id\nJOIN Products p ON l.product_id = p.product_id\nWHERE l.sector_id = $sector_id -- <-- Filtra usando la tua variabile\nORDER BY l.timestamp DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Dettaglio prodotti",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Movimentazione prodotto specifico: $product_id",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "smart_warehouse",
       "rawSql": "SELECT \n  l.timestamp AS \"Data/Ora\",\n  u.username AS \"Operatore\",\n  s.name AS \"Settore Coinvolto\",\n  p.name AS \"Prodotto\",\n  l.quantity AS \"Quantità Movimentata\"\nFROM StockMovementsLog l\nJOIN Users u ON l.user_id = u.user_id\nJOIN Sectors s ON l.sector_id = s.sector_id\nJOIN Products p ON l.product_id = p.product_id\nWHERE l.product_id IN ($product_id) -- Filtro dinamico\nORDER BY l.timestamp DESC;"
      }
     ]
    },
    {
     "title": "Distribuzione del prodotto:  $product_id",
     "type": "piechart",
     "description": "Mostra quanto è distribuito un prodotto sui settori del magazzino",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "smart_warehouse",
       "rawSql": "SELECT \n  p.name || ' - ' || s.name AS \"Prodotto e Settore\",\n  i.quantity\nFROM Inventory i\nJOIN Sectors s ON i.sector_id = s.sector_id\nJOIN Products p ON i.product_id = p.product_id\nWHERE i.product_id IN ($product_id) AND i.quantity > 0;"
      }
     ]
    },
    {
     "title": "Stock: $product_id",
     "type": "stat",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "repeat": "product_id",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "smart_warehouse",
       "rawSql": "SELECT \n  now() as time,\n  p.name as \"Prodotto\",\n  SUM(i.quantity) as \"Stock\",\n  (p.reorder_threshold) as \"Soglia riordino\" \nFROM Inventory i\nJOIN Products p ON i.product_id = p.product_id\nWHERE p.product_id IN ($product_id)\nGROUP BY p.name, p.reorder_threshold"
      }
     ]
    }
   ]
  }
 ]
}